### ISSUE TITLE
Buffering does not build on stable rustc

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/buffering#1]
@skrap Thanks for the bug report. As you mentioned in [this issue](https://github.com/jbaublitz/neli/issues/22), there is a feature flag in buffering preventing it from building on a stable rustc. This should not be there anymore as the custom macro attribute feature has been stabilized for a bit. I'm going to remove this from buffering and update CI to test both `stable` and `nightly` moving forward. I'll let you know once the new buffering version is released. As you're looking to build `neli`, just do a `cargo update` once `buffering` has been released and rebuild.

**Comment by jbaublitz** [comment]
@skrap All set, closing this out. Reach out here if you have any issues related to this and I'll reopen.

**Comment by skrap** [comment]
Thanks!  Much appreciated!
